### PR TITLE
Return placeholder images from the backend

### PR DESCRIPTION
**Pull request by farktronix**
I already did this work but I need to send a new PR

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
On it! I'll review the changes as soon as possible!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
I don’t think it’ll work. Make sure it passes all checks, and  only then you’ll be able to merge the PR.

**Comment by farktronix** [comment]
It passes all checks now

**Review by farktronix — COMMENTED** [review]
Yep this works fine.

**Review by farktronix — COMMENTED** [review]
Removed

**Comment by farktronix** [comment]
Guess I'm stuck.

**Pull request closed without merging**
